import numpy as np

numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)
print(numbers1)
print(numbers2)
print("\n" + 20 * '-' + "\n")

print("iki array toplamı ", numbers1 + numbers2)
print("arraye ekleme ", numbers1 + 10)
print("iki array çıkarma ", numbers1 - numbers2)
print("array çıkartma ", numbers1 - 10)
print("array çarpma ", numbers1 * numbers2)
print("array çarpma ", numbers1 * 10)
print("array bölü ", numbers1 / numbers2)
print("array bölü ", numbers1 / 10)
print("\n" + 20 * '-' + "\n")

print("sin array ", np.sin(numbers1))
print("cos array ", np.cos(numbers1))
print("sqrt array ", np.sqrt(numbers1))
print("log array ", np.log(numbers1))
print("\n" + 20 * '-' + "\n")

m_numbers1 = numbers1.reshape(2,3)
m_numbers2 = numbers2.reshape(2,3)
result1 = np.stack((m_numbers1, m_numbers2))
result2 = np.vstack((m_numbers1, m_numbers2))
result3 = np.hstack((m_numbers1, m_numbers2))
print('concatenate sonucu:', result1)
print('vertical stack sonucu:', result2)
print('horizontal stack sonucu:', result3)
print("\n" + 20 * '-' + "\n")

print('concatenate ndim:', result1.ndim)
print('vstack ndim:', result2.ndim)
print('hstack ndim:', result3.ndim)
print('concatenate shape:', result1.shape)
print('vstack shape:', result2.shape)
print('hstack shape:', result3.shape)
print("\n" + 20 * '-' + "\n")

new_array = np.array([1, 2, 3, 4, 5, 6])
print("diziyi 3 eşit parçaya ayır: ", np.split(new_array, 3))
print("ayrılan parçalara erişim: ", np.split(new_array, 3)[0])
print("\n" + 20 * '-' + "\n")

print("numbers1 > 50 bool:\n   ", m_numbers1 > 50)
print("numbers1 > 50 göster:\n   ", m_numbers1[m_numbers1 > 50])
print("numbers1 % 2 == 0:\n   ", m_numbers1[m_numbers1 % 2 == 0])
print("\n" + 20 * '-' + "\n")

np_array = np.random.randint(-20, 20, 20)
np_multi = np_array.reshape(5, 4)
np_multi = np_multi * 3
print('np_multi:\n', np_multi)
ciftler = np_multi[np_multi % 2 == 0]
print('ciftler: ', ciftler)
print('ciftler > 0: ', ciftler[ciftler > 0])
print("\n" + 20 * '-')